version: '3.8'

networks:
    net_service:
        external:
            name: net_service

services:
    apache:
        image: 25watts/symfony:5.x
        ports:
            - 8001:80
        volumes:
            - .:/var/www/html
        networks:
            - net_service